export { default as About } from './About/About'
export { default as Creative } from './Creative/Creative'
export { default as Home } from './Home/Home'
export { default as NativeApp } from './NativeApp/NativeApp'
export { default as PrivacyPolicy } from './PrivacyPolicy/PrivacyPolicy'
