export { default as Button } from './Button/Button'
export { default as Footer } from './Footer/Footer'
export { default as Head } from './Head/Head'
export { default as Loader } from './Loader/Loader'
export { default as Logo } from './Logo/Logo'
export { default as Navbar } from './Navbar/Navbar'
